POST https://10.9.1.72:20203/enadmin/api/open/v1/token
Content-Type: application/json
# 编码方式
Content-Encoding: utf-8

{
  "appId": "202604101324332042473790244559356000",
  "appSecret":  "l7z032nu5ssttquxb080o64x33b09nvorbg4zrhf8m52x4ma0zz9c79lrpf92xbf"
}

###
POST https://10.9.1.72:20203/enadmin/api/open/v1/contact/dept/list
Content-Type: application/json
# 编码方式
Content-Encoding: utf-8
accessToken:enaccess-e43d0a3bf309d53c73a81ced2234aeb5

{

}

###
POST https://10.9.1.68:20203/enadmin/api/open/v1/contact/dept/create
Content-Type: application/json
# 编码方式
Content-Encoding: utf-8
accessToken:enaccess-b8e6853e95a5a8f89d5566a5e7dd3010

{

  "name": "站点用户",
  "parentId": "0",
  "path": "/站点用户",
  "type": "0",
  "description": ""
}
