POST https://10.9.1.72:20203/enadmin/api/open/v1/token
Content-Type: application/json
# 编码方式
Content-Encoding: utf-8

{
  "appId": "202604101324332042473790244559356000",
  "appSecret":  "l7z032nu5ssttquxb080o64x33b09nvorbg4zrhf8m52x4ma0zz9c79lrpf92xbf"
}


###
POST https://10.9.1.72:20203/enadmin/api/open/v1/contact/user/list
Content-Type: application/json
# 编码方式
Content-Encoding: utf-8
accessToken:enaccess-3bf35ee4895c5d58180869e24b3a8d53

{

}


###
POST https://10.9.1.72:20203/enadmin/api/open/v1/contact/dept/list
Content-Type: application/json
# 编码方式
Content-Encoding: utf-8
accessToken:enaccess-01268e01281a21e1b482916e6819cd61

{

}

###
POST https://10.9.1.72:20203/enadmin/api/open/v1/contact/servicegroup/list
Content-Type: application/json
# 编码方式
Content-Encoding: utf-8
accessToken:enaccess-d97d1046dd8dd727d834c5b4fe0d05da

{

}

###
POST https://10.9.1.72:20203/enadmin/api/open/v1/contact/dept/create
Content-Type: application/json
# 编码方式
Content-Encoding: utf-8
accessToken:enaccess-d2973f8c548832817d3c5f03f493ed45

{

  "name": "财务中心",
  "parentId": "202604101320332042472784878279126000",
  "type": "0",
  "description": ""
}


###
POST https://10.9.1.72:20203/enadmin/api/open/v1/contact/dept/update/202604101320332042472784878279126000
Content-Type: application/json
# 编码方式
Content-Encoding: utf-8
accessToken:enaccess-01268e01281a21e1b482916e6819cd61

{
  "id": "202604101320332042472784878279126000",
  "name": "深圳市穗彩科技开发有限公司",
  "parentId": "0",
  "type": "0",
  "description": ""
}

###
POST https://10.9.1.72:20203/enadmin/api/open/v1/contact//user/create
Content-Type: application/json
# 编码方式
Content-Encoding: utf-8
accessToken:enaccess-e7b0bdca4760c5dd41594ac761c17522

[{
  "username":"ying",
  "name":"test",
  "password":"123456",
  "mobile":"18634358909",
  "email":"echoying@genlot.com",
  "groups":["0"],
  "description":"",
  "gender":"",
  "birthDay":"",
  "idCard":""
}]
