# 基础镜像
#FROM  openjdk:8-jre
FROM eclipse-temurin:8-jre
# author
MAINTAINER ruoyi

# 不要 VOLUME /home/ruoyi：匿名卷会挡住镜像/绑定里的新 jar
# 创建目录
RUN mkdir -p /home/ruoyi
# 指定路径
WORKDIR /home/ruoyi
# 复制jar文件到路径
COPY ./jar/ruoyi-modules-yianlian.jar /home/ruoyi/ruoyi-modules-yianlian.jar
# 启动系统服务
ENTRYPOINT ["java","-Xms256m","-Xmx512m","-Duser.timezone=Asia/Shanghai","-jar","ruoyi-modules-yianlian.jar"]